### ISSUE TITLE
"KeyboardAvoidingView-Swift.h" is missing when installing the library from Cocoapods

### ISSUE THREAD

**Issue by andriichernenko** [APUtils/KeyboardAvoidingView#1]
Hello!

First of all, thank you for your work! I have tested this library and it works great!

One minor problem though. When installing from Cocoapods, `KeyboardAvoidingView-Swift.h` is missing in `KeyboardAvoidingViewLoader.m`. As a result, the build fails.

Could you please fix this and update the pod?

**Comment by anton-plebanovich** [comment]
Hello @andriichernenko , it works for me using Cocoapods for my test project. Please check if you are using latest version in your `Podfile` `pod "KeyboardAvoidingView", '~> 2.2'` and also try to run `pod update KeyboardAvoidingView`. 

`KeyboardAvoidingView.h` shouldn't be included into pods project, it's Carthage header file.

Please also check that you have `use_frameworks!` option in your `Podfile`.

**Comment by andriichernenko** [comment]
I updated to the latest version, 2.2.6. As for the `use_frameworks!`, I'd like to avoid it if possible. Since [Cocoapods 1.5.0](http://blog.cocoapods.org/CocoaPods-1.5.0/) it is possible to link Swift dependencies as static frameworks, which has benefits such as improved app launch time, etc.

Does KeyboardAvoidingView support being linked as a static library?

**Comment by andriichernenko** [comment]
It's actually not `KeyboardAvoidingView.h` that's missing, but rather `KeyboardAvoidingView-Swift.h`:
```
/Users/ac/Projects/TheProject/Pods/KeyboardAvoidingView/KeyboardAvoidingView/Classes/KeyboardAvoidingViewLoader.m:8:9: 'KeyboardAvoidingView/KeyboardAvoidingView-Swift.h' file not found
```

My bad, sorry for misreporting the issue.

**Comment by anton-plebanovich** [comment]
I'll investigate, thanks for report

**Comment by anton-plebanovich** [comment]
@andriichernenko Please check latest version `KeyboardAvoidingView (2.2.7)`. It should support building into static library.

**Comment by andriichernenko** [comment]
@anton-plebanovich The issue has been fixed now, the project builds fine.
Appreciate the quick response, thanks a lot!
